#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$app = require_once __DIR__.'/bootstrap/app.php';

// Створюємо application instance з builder
$application = $app->create();

$kernel = $application->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new ArgvInput,
    new ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
